import { z } from 'zod';

export const TelemetryEventTypeSchema = z.enum([
  'game.ready',
  'game.started',
  'input.received',
  'player.moved',
  'player.jumped',
  'movement.crouch.entered',
  'player.fired',
  'projectile.spawned',
  'collision.detected',
  'enemy.fired',
  'enemy.hit',
  'enemy.cleared',
  'item.spawned',
  'item.collected',
  'pickup.collectible.collected',
  'pickup.collectible.state_changed',
  'pickup.weapon_supply.verified',
  'provider.deepseek_authoritative_draft.validated',
  'review.oracle_final_gate.approved',
  'runtime.manifest_binding.verified',
  'runtime.module_load_receipt.verified',
  'runtime.plan_coverage.verified',
  'scene.ordered_segments.verified',
  'scene.visual_presentation_metadata.verified',
  'spawn.enemy_wave.ordered',
  'spawn.explicit_declarations.verified',
  'spawn.stop_on_boss_defeat.verified',
  'ui.failure_restart.verified',
  'ui.hud_boss_health.verified',
  'ui.hud_current_weapon.verified',
  'ui.hud_player_health.verified',
  'enemy.flying_right_entry.verified',
  'enemy.patrol_infantry.verified',
  'feedback.victory_declaration.verified',
  'generation.fallback_policy_fail_closed.verified',
  'goal.boss_unlock.verified',
  'hazard.spawned',
  'hazard.falling_area.verified',
  'hazard.timed_explosion.verified',
  'player.damaged',
  'health.damage_invulnerability.activated',
  'health.damage_invulnerability.blocked',
  'checkpoint.reached',
  'rules.checkpoint_restore.restored',
  'rules.encounter_gate.closed',
  'rules.retry_count.changed',
  'rules.state_transition_graph.verified',
  'level.segment.completed',
  'score.changed',
  'survival_time.changed',
  'objective.completed',
  'game.won',
  'game.lost',
  'game.restarted'
]);

/** Runtime authoritative telemetry event; DSL 和模型输出不能伪造该结果。 */
export const TelemetryEventSchema = z.object({
  type: TelemetryEventTypeSchema,
  timestamp_ms: z.number().int().min(0),
  frame: z.number().int().min(0),
  payload: z.record(z.string(), z.unknown()).optional()
});

export type TelemetryEvent = z.infer<typeof TelemetryEventSchema>;
